name: planner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  shared_preferences: ^2.0.15
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/card-images/
