name: planner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.2.1+6
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.5.3
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.7
  flutter_timer_countdown: ^1.0.7
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/auth/
    - assets/icons/
    - assets/task-icons/
    - assets/card-images/
