class CheckListCard {
  List checklistData = [
    'Personal',
    'Legal',
    'Budget',
    'Venue',
    'Suppliers',
    'Rings',
    'Invitations',
    'Photo & Video',
    'Music',
    'Food & Drink',
    'Attire & Beauty',
    'Guests',
    'Gifts',
    'Decor',
    'Day of the Wedding',
    'Ceremony',
    'Honeymoon',
    'After Wedding',
  ];

  List checkListDataImgLink = [
    "assets/card-images/Personal-card.png",
    "assets/card-images/legal-card.png",
    "assets/card-images/budget-card.png",
    "assets/card-images/venue-card.png",
    "assets/card-images/suppliers-card.png",
    "assets/card-images/rings-card.png",
    "assets/card-images/Invitations-card.png",
    "assets/card-images/photovideo-card.png",
    "assets/card-images/Music-card.png",
    "assets/card-images/FoodDrink-card.png",
    "assets/card-images/AttireBeauty-card.png",
    "assets/card-images/guests-card.png",
    "assets/card-images/Gift-card.png",
    "assets/card-images/decor-card.png",
    "assets/card-images/Wedding-card.png",
    "assets/card-images/ceremony-card.png",
    "assets/card-images/Honeymoon-card.png",
    "assets/card-images/afterWedding-card.png",
  ];
}
